### ISSUE TITLE
Distinct().order_by('field') results in ProgrammingError

### ISSUE THREAD

**Issue by wadevries** [incuna/django-pgcrypto-fields#204]
Platform: macOS Catalina
Python: 3.6.9
Django: 2.2.11

Given a model with encrypted fields, doing;

`EncryptedModel.objects.distinct().order_by('encrypted_field')`

Results in 
```
django.db.utils.ProgrammingError: syntax error at or near "Version"
LINE 59: Version: GnuPG v1
```

The syntax error refers to some (seemingly random) part of the armored key in the SQL. 

Interestingly, this does not occur when you `distinct` on the `encrypted_field`: 

`EncryptedModel.objects.distinct('encrypted_field').order_by('encrypted_field')`

Works fine. So does

`EncryptedModel.objects.distinct()`.

I've created a PR #203 with a breaking test, but I don't know where to start fixing this.

**Comment by wadevries** [comment]
I encoutered this bug through usage of Django admin's AllValuesFieldListFilter:

https://github.com/django/django/blob/167699278806b21757104acf0ff0570f673d44c7/django/contrib/admin/filters.py#L385

**Comment by wadevries** [comment]
Apparently this bug doesn't trigger in Django >= 3.0, according to Travis
https://travis-ci.org/github/incuna/django-pgcrypto-fields?utm_medium=notification&utm_source=github_status

**Comment by maestrofjp** [comment]
@wadevries this is just a variation of the limitation using this library with Django 2.x as documented here:

https://github.com/incuna/django-pgcrypto-fields#distinctencrypted_field_name

The version #s of Django may need to be updated as I believe Django 2.2 was not official at the time of the documentation being written.
