### ISSUE TITLE
Remove support for Django 1.11

### ISSUE THREAD

**Issue by pauloxnet** [incuna/django-pgcrypto-fields#214]
Django 1.11 has reached the end of extended support on April 1, 2020.

https://www.djangoproject.com/weblog/2020/apr/01/bugfix-releases/

**Comment by peterfarrell** [comment]
As noted in the README under Requirements:

Last version of this library that supports Django 1.8.x, 1.9.x, 1.10.x was django-pgcrypto-fields 2.2.0.
