### ISSUE TITLE
[Need help] when using update with F() getting pgp_sym_encrypt(numeric, unknown) does not exist

### ISSUE THREAD

**Issue by manojahi** [incuna/django-pgcrypto-fields#244]
I am using django-pgcrypto-fields symmetric encryption in DB.
I have following update query

```
MyTable.objects.filter(some_code=some_code).update(
                    some_value=(some_price * F('some_units')),
                    updated_on=datetime.now()
                )
```

I am getting the following issue ```psycopg2.errors.UndefinedFunction: function pgp_sym_encrypt(numeric, unknown) does not exist```

I am not sure if this is the issue with the library or something with my code.

**Comment by peterfarrell** [comment]
@manojahi is `some_value` an encrypted field?  If so, you can't use `F()` functions with it as that value is encrypted in the DB.

**Comment by Suganya1908** [comment]
@peterfarrell I'm getting the same error when creating the object

model.py
class Session(AuditUuidModelMixin, models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    duration_min = models.IntegerField()
    price = DecimalPGPSymmetricKeyField(max_digits=10, decimal_places=2)
    is_active = models.BooleanField(default=True)
    
    when I do post-operation I'm getting the same error
    
    @manojahi  did u find any solution? 
    
    Can you guys help me out?

**Comment by peterfarrell** [comment]
@Suganya1908 I'd need a stack trace. Usually, this means you do not have pgcrypto installed in Postrgres:

https://github.com/incuna/django-pgcrypto-fields/blob/master/README.md#psycopg2errorsundefinedfunction-function-pgp_sym_encryptnumeric-unknown-does-not-exist

**Comment by Suganya1908** [comment]
@peterfarrell when I use this command select * from pg_available_extensions I'm able to see the pgcrypto already available.

can you suggest to me any link where I can find a proper installation guide.?

**Comment by peterfarrell** [comment]
@Suganya1908  Will you please sure a full stack trace of the error you are getting?  Also, what version of Django are you running?
