### ISSUE TITLE
Remove support for python3.5

### ISSUE THREAD

**Issue by kevinetienne** [incuna/django-pgcrypto-fields#261]
[Python 3.5 end-of-life is next month](https://devguide.python.org/#status-of-python-branches) I suggest to drop the support. It would allow to update twine (see pyup.io build status https://github.com/incuna/django-pgcrypto-fields/pull/260) to the last version too as [the library deprecated support for it last year](https://github.com/pypa/twine/commit/06663c5787a16250debf80aad3a9047fa25e52cd).

**Comment by peterfarrell** [comment]
Seems very reasonable.
