### ISSUE TITLE
Custom methods to `get_or_create`, `update_or_create`

### ISSUE THREAD

**Issue by kevinetienne** [incuna/django-pgcrypto-fields#27]
At the moment using django `get_or_create` or `update_or_create` doesn't work as some values might be encrypted/hashed. We can have a mixin which would override those methods from django.

**Comment by Ian-Foote** [comment]
We also need to include a `create` method. If an encrypted field is meant to be unique, we need to do a lookup to avoid accidentally creating duplicates.

**Comment by peterfarrell** [comment]
This enhancement request will be overcome by events (OBE) when the changes in the `new_auto_decryption` branch is merged into master.

**Comment by peterfarrell** [comment]
Fixed in v2.4.0
