### ISSUE TITLE
Question - How to use a different hashing algorithm?

### ISSUE THREAD

**Issue by 9mido** [incuna/django-pgcrypto-fields#278]
The default pgcrypto extension is PGP (public key/privacy key) output looks like:

\xc30d0407030286e239c36fe48d126dd24401086aecb7805d0e52fc77c32bc341f566153ee9e291d11f8972a6fd63a44282b5a7df09fad63d0bbd1eb1374980a9e10e13d2987a1289e193a749f496aec0195e1eb5e3

Not sure if this is the most secure by default. If improved algorithms are found in the future, how would you configure them?

If not using PGP and instead a one way hash, why not use other options like bcrypt are argon2, pbkdf2, scrypt, etc. instead of SHA. 

Perhaps an improvement to django-pgcrypto-fields would be to configure what types of algorithms you would want to use? Or is there already a way to configure this with postgres or something?

**Comment by peterfarrell** [comment]
This is a duplicated of #135 which had a "help wanted" label on to improve this library.

**Comment by 9mido** [comment]
Thanks did not see that other one.

**Comment by peterfarrell** [comment]
@9mido PRs welcome on #135
