### ISSUE TITLE
cast_type of DateTimePGPSymmetricKeyField does not allow for dumpdata exports exporting timezone aware datetimes.

### ISSUE THREAD

**Issue by steezeburger** [incuna/django-pgcrypto-fields#307]
Extremely easy to override with a custom class when using Postgres as your database
```
class CustomDateTimePGPSymmetricKeyField(fields.DateTimePGPSymmetricKeyField):
    """
    Overriding cast_type so `dumpdata` command exports timezone aware datetimes.
    """
    cast_type = 'TIMESTAMPTZ'
```
but maybe this could be a setting? Or it could look at current USE_TZ setting?

**Comment by peterfarrell** [comment]
@steezeburger 

Django treats all datetimes with timezone so this likely a bug by using the wrong cast type. Ref:

https://docs.djangoproject.com/en/3.1/topics/i18n/timezones/#postgresql

I think we can safely change over to `TIMESTAMPTZ` without any ill effects given that is what Django always uses. A PR is welcome to fix this.

**Comment by steezeburger** [comment]
Ah beat me to it! I forgot I forked this and fixed, but never got the tests running and forgot to submit the PR haha. Thanks for this!

**Comment by peterfarrell** [comment]
@steezeburger still need to do a release -- install from master if you want it today.
