### ISSUE TITLE
Dynamic PGCRYPTO_KEY

### ISSUE THREAD

**Issue by lucifurtun** [incuna/django-pgcrypto-fields#310]
Is there any option to use a key in a dynamic manner? For example, if there's a need to encrypt/decrypt data with different keys depending on some factors, is this possible using this package?

**Comment by peterfarrell** [comment]
Depends on what you mean, keys are associated with datasources so you can have different keys if you have multiple databases in one app:

```
DATABASES = {
    # This db will use the default keys above
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'pgcryto_fields',
        'USER': 'pgcryto_fields',
        'PASSWORD': 'xxxx',
        'HOST': 'psql.test.com',
        'PORT': 5432,
        'OPTIONS': {
            'sslmode': 'require',
        }
    },
    'diff_keys': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'pgcryto_fields_diff',
        'USER': 'pgcryto_fields_diff',
        'PASSWORD': 'xxxx',
        'HOST': 'psqldiff.test.com',
        'PORT': 5432,
        'OPTIONS': {
            'sslmode': 'require',
        },
        'PGCRYPTO_KEY': 'djangorocks',
        'PUBLIC_PGP_KEY': open(DIFF_PUBLIC_PGP_KEY_PATH, 'r').read(),
        'PRIVATE_PGP_KEY': open(DIFF_PRIVATE_PGP_KEY_PATH, 'r').read(),
    },
}
```

However, there is no support for different keys on the row level.

**Comment by lucifurtun** [comment]
@peterfarrell , I meant different keys depending on the context. Let's say we have a model called `University` and another on called `Student` which is related to `University`. Now, if we want to encrypt the name of the student with a key provided by the university, is it possible to do that?

**Comment by peterfarrell** [comment]
@lucifurtun

In general, there are three approaches to multitenancy databases:
 
1.  Isolated Approach: Separate databases for each tenant

1.  Semi Isolated Approach: One Database, Separate Schemas for each tenant

1.  Shared Approach: Shared Database, Shared Schema for all tenants.  Essentially -- you link a foreign key on all objects to a `University` object.

In your example, you are describing the third option - Shared Approach. I'm sure it's possible to do however this library doesn't support your example use case of multiple tenants in a shared database with each tenant having their own key.

There are some Django libraries that are available to solve multitenancy in different ways. I have not personally used any of them.  You might be able to modify this library to change the key based on the tenant.

PRs welcome.

**Comment by lucifurtun** [comment]
Ok, got it. Thank you!
