### ISSUE TITLE
function digest(unknown, unknown) does not exist

### ISSUE THREAD

**Issue by Pikeman85** [incuna/django-pgcrypto-fields#33]
It seems to be having a problem with the function digest and the correct hashing algorithm. Is there some dependency missing that would cause this, or misconfiguration?

I am trying to create a TextDigestField

**Comment by KevinEtienne** [comment]
Thanks for reporting this, is it possible to have the stacktrace? I think your postgres database hasn't the [`pgcrypto`](https://github.com/incuna/django-pgcrypto-fields/blob/bac526ebf249529bb3b44ae93b76d1e0aa6a8c37/pgcrypto/migrations/0001_add_pgcrypto_extension.py#L4) [extension](http://www.postgresql.org/docs/devel/static/pgcrypto.html) installed. When the app is in `INSTALLED_APPS` a migration is available and you should be able to run it.

**Comment by shacker** [comment]
I did not end up with a migration auto-created to install the extension. However I was able to create one manually:

```
    operations = [
        migrations.RunSQL("CREATE EXTENSION pgcrypto;"),
    ]
```

**Comment by peterfarrell** [comment]
Issue resolved. Django-pgcrypto auto installs the extension in 0001 migration for you if it does not exist.
