### ISSUE TITLE
DateTimePGPSymmetricKeyField does not save with timezone info, is this a defect?

### ISSUE THREAD

**Issue by steezeburger** [incuna/django-pgcrypto-fields#345]
imagine some field:
```
expires_at = fields.DateTimePGPSymmetricKeyField(null=True)
```

set equal to:
```
from datetime import timedelta
from django.utils.timezone import now
...
expires_at = now() + timedelta(seconds=token['expires_in'])
```

I noticed there was an issue when I got the error:
```
can't compare offset-naive and offset-aware datetimes
```
from this call on my model:
```
@property
def is_expired(self):
    return self.expires_at < now()
```

Inspecting the unencrypted datetime next to a never encrypted datetime -- you can see the never encrypted datetime still has timezone information:
![Screen Shot 2021-04-19 at 9 34 05 PM](https://user-images.githubusercontent.com/5599073/115334048-e61fc300-a157-11eb-8d7b-e2136f00db11.png)

I can remedy this by refacroting my `is_expired` method to:
```
import pytz
...
@property
def is_expired(self):
    return self.expires_at.replace(tzinfo=pytz.UTC) < now()
```
but I was curious if this was a defect.

Thanks for your time! :)

**Comment by peterfarrell** [comment]
This was fixed in #307 which is in master but not released on PyPi yet.
