### ISSUE TITLE
How to retrieve raw encrypted value?

### ISSUE THREAD

**Issue by steezeburger** [incuna/django-pgcrypto-fields#346]
I would like to show the encrypted values for Django admin users that are not super users, and only show the decrypted values to super users, but I'm not sure how to go about this. Do you have any guidance?

I was thinking I could extend `admin.ModelAdmin` class somehow or maybe create custom admin Forms and handle it that way, but I'm not sure how to access the encrypted value at this point when the model fields are already decrypted.

**Comment by steezeburger** [comment]
One option: I think I can create my own `ModelAdmin.get_exclude` method and could hide the fields that I know are encrypted manually. Something like
```
def get_exclude(self, request, obj=None):
    if not request.user.is_superuser:
        return ('content',)
``` 

But is there some way for me to inspect the obj and return a list of fields that were encrypted?

**Comment by peterfarrell** [comment]
@steezeburger there's no functionality in this library to do this as the library is specifically to make field level db encryption transparent to your Django application.

Django has a meta api that you can use to introspect your model object:

https://docs.djangoproject.com/en/3.2/ref/models/meta/

All encrypted fields offered by this library extend  the `PGPMixin` class which you can use to identify which fields are encrypted.  Hash fields extend `HashMixin` but you should not need to worry about them as they are one way functions.
