### ISSUE TITLE
ExternalRoutineInvocationException: Need password for secret key

### ISSUE THREAD

**Issue by guiflemes** [incuna/django-pgcrypto-fields#351]
I made all the configurations described in the README to use ` PGPPublicKeyField`.
I created my public and private key, however when I make a query this error is thrown, `ExternalRoutineInvocationException: Need password for secret key`

Am I missing something?

**Comment by peterfarrell** [comment]
See:

https://github.com/incuna/django-pgcrypto-fields/blob/master/README.md#limitations

PR welcomed on:

https://github.com/incuna/django-pgcrypto-fields/issues/89

**Comment by peterfarrell** [comment]
This is a duplicate of #89. Closing.
