### ISSUE TITLE
" filter() " is not working.

### ISSUE THREAD

**Issue by Youngsoo77** [incuna/django-pgcrypto-fields#40]
I was testing to use the 'filter()'.

While I was working on a simple example, I could not get any values ​​like this:

What did I do wrong? Or is there a manual error?

Please Help me... 

youngsoo

- django==1.10
- python==3.4.5

```ipython
>>> MyModel.objects.filter().first().pgp_pub_field
'hello, world!\r\n안녕하세요.'
>>> from pgcrypto.aggregates import PGPPublicKeyAggregate
>>> my_models = MyModel.objects.annotate(PGPPublicKeyAggregate('pgp_pub_field'))
>>> my_models
<QuerySet [<MyModel: #1>, <MyModel: #2>]>
>>> my_models.filter(pgp_pub_field='h')
<QuerySet []>
>>> my_models.filter(pgp_pub_field__decrypted='h')
<QuerySet []>
>>> my_models.filter(pgp_pub_field__decrypted='haa')
<QuerySet []>
>>> my_models.filter(pgp_pub_field__decrypted='1111')
<QuerySet []>
```

**Comment by kmryu** [comment]
I have the same problem.

**Comment by KevinEtienne** [comment]
Than you. As far as I can see `my_models.filter(pgp_pub_field='h')` will not work as you have to explicitly use the `decrypted` lookup to query the decrypted value of the field.

```python
>>> my_models.filter(pgp_pub_field__decrypted='h')
>>> my_models.filter(pgp_pub_field__decrypted='haa')
>>> my_models.filter(pgp_pub_field__decrypted='1111')
```
The 3 querysets above can work if any of your two instances `<QuerySet [<MyModel: #1>, <MyModel: #2>]>` have either `h`, `haa` or `1111` as values.

I can see that your first object has `'hello, world!\r\n안녕하세요.'` as value for `pgp_pub_field`. You can then filter with the following and you should have an object back:

```python
>>> my_models.filter(pgp_pub_field__decrypted='hello, world!\r\n안녕하세요.')
```
