### ISSUE TITLE
Python 2.7 compatibility?

### ISSUE THREAD

**Issue by Protosac** [incuna/django-pgcrypto-fields#45]
It appears this is Python 3? Is this supposed to be compatible with old Python 2.7 code? I'm getting the:

`TypeError: super() takes at least 1 argument (0 given)`

... after installing and running the package. (Django 1.9.8)

**Comment by KevinEtienne** [comment]
Hi @Protosac, unfortunately this is not compatible with python2.

Are you by chance starting a new project with `Django 1.9.8`. And are you aware that `Django` will drop support for it in the `2.0` release?  (however it will be not an issue if you plan to use `1.11`.)

**Comment by meshy** [comment]
It's probably a good idea to add the `Programming Language :: Python :: 3 :: Only` trove classifier to `setup.py`.

I wonder if it's also worth adding something that fails early on a python 2 installation too?

**Comment by KevinEtienne** [comment]
Trove should be straightforward to add.
Maybe we can add an assert somewhere to check the python version?

**Comment by Protosac** [comment]
@KevinEtienne Yes I've learned about that but that's kinda the pickle. To upgrade to Django 1.10 I need to upgrade from an outdated pgcrypto derived module that's no longer being maintained. I was trying to restore *this* one but it looks like we're out of luck if I don't customize this for Python 2 compatibility. Thanks a lot for the update.

**Comment by KevinEtienne** [comment]
@Protosac a temporary solution could be to fork this project and to run https://pypi.python.org/pypi/3to2?

**Comment by Protosac** [comment]
On @KevinEtienne advice I attempted this weekend to make this package Python2 compatible. It seems to work well when I use it on a Python 2.7 django app and models. I wanted to ask whether any of you have a few minutes to spare this week to give it a quick review? If you don't have the time I completely understand, but I figured no harm in asking. You would be the best persons to know whether I've broken anything in the module. The amount of actual code changes is very small.

Any feedback would be greatly appreciated. The last thing I want is to implement a poor hack and put any of my data at risk.

 https://github.com/diveone/django-pgcrypto-fields/pull/1

**Comment by KevinEtienne** [comment]
Hi @Protosac I've commented on your fork. I think it will help to activate travis and to see if tests pass.

**Comment by Protosac** [comment]
Thanks again! I greatly appreciate you taking the time to give it a look! I'll be making the updates you suggested and this week I'll get this into our app so we can upgrade finally. 

You're awesome, thanks so much.

**Comment by peterfarrell** [comment]
https://github.com/incuna/django-pgcrypto-fields/pull/46#issuecomment-427178670

> Given that the last version of Django (1.11) to support Python 2 reaches EOL in January of 2020, I'm hesitant to vote to accept this PR. We're looking at 14 months before Python 2 is no longer applicable for Django development.

Closing.
