### ISSUE TITLE
Add support to hash fields to optionally base hash value off another field value

### ISSUE THREAD

**Issue by peterfarrell** [incuna/django-pgcrypto-fields#47]
We wanted to run a new feature by you all to see if it's worth for us to do a PR.

We want to add support to the hash fields that optionally bases the value for the hash off the value of another field.  This would be useful to pre-compute a hash based on the value from another model field and not have to worry about updating the hash when the other field value changes. Essentially, it ensures the hash is always based on the value of a sibling field.

Example:

```python
class User(models.Models):
    first_name = fields.TextPGPSymmetricKeyField(max_length=20, verbose_name='First Name')
    first_name_hashed = fields. TextHMACField(original='first_name') 
```

In the above example, if you specify the optional `original` attribute -- it would take the unencrypted value from the `first_name` model field as the input value to create the hash. If you didn't specify an `original` attribute, the field would work as it does now and would remain backwards compatible.

Let us know if you would be willing to accept a PR for this feature.

**Comment by KevinEtienne** [comment]
Hi @peterfarrell, that sounds like a great idea to avoid to manually updating the cryped field.
Unfortunately, I've left Incuna and I don't have power over this repository.

@maxpeterson can you make us contributors please? Would it be possible to do the same with pypi to push new release?

If we don't have an answer we can fork it but we will have to release it under a new name. It might help #46 to be merged.

**Comment by peterfarrell** [comment]
@KevinEtienne If we don't hear back from @maxpeterson by the end of the week, I suggest we go ahead and move forward with your suggestion to fork and release on PyPi under a new name.

**Comment by KevinEtienne** [comment]
Looks like I had already a fork in my account, let's add issues/PRs in https://github.com/KevinEtienne/django-pgcrypto-fields

**Comment by KevinEtienne** [comment]
Back on track we're both contributors (thanks @maxpeterson and @meshy).

**Comment by peterfarrell** [comment]
Thanks @maxpeterson and @meshy

**Comment by peterfarrell** [comment]
Added in 2.1.0 release.
