### ISSUE TITLE
Custom manager for Decrypt annotate

### ISSUE THREAD

**Issue by KevinEtienne** [incuna/django-pgcrypto-fields#5]
Add a custom manager to include the `Decrypt` annotate in `get_queryset`.

**Comment by peterfarrell** [comment]
@mpwoodward, I think we might have something for this right?

**Comment by mpwoodward** [comment]
Yep we have something along these lines. Not quite as transparent as maybe the suggestion here implicates, but for performance reasons you might not want it to be quite that automatic so you can still judiciously choose whether or not you need to decrypt anything.

**Comment by KevinEtienne** [comment]
That sounds good what did you do? It sounds like the call should be explicit to decrypt things (ex: `Model.objects.decrypt().filter...`). Maybe this `decrypt` method manager should `decrypt` all encrypted fields by default and can accept a list to allow to narrow the list down if necessary.
And maybe using the model without the model manager shouldn't do any extra query?

At the moment every time an encrypted attribute is accessed we make a query to the database.

**Comment by peterfarrell** [comment]
This issue could be closed if PR #44 is accepted and merged.

**Comment by peterfarrell** [comment]
@KevinEtienne I think this can be closed with the release of 2.1.0
