### ISSUE TITLE
Release 2.1.1 

### ISSUE THREAD

**Issue by peterfarrell** [incuna/django-pgcrypto-fields#51]
I checked in a PR for Django 2.0 support. I upgraded the requirements and travis to get the build to run successfully again. I have tagged this as 2.1.1.

Please release what is in master to PyPi as release 2.1.1 at your earliest convenience or add my PyPi user `peterfarrell-atdsaa` to be able to push releases to the cheese shop.

@kevinetienne @maxpeterson @meshy @cyanc @Ian-Foote

**Comment by kevinetienne** [comment]
It doesn't seem I have access too, but I'll be happy to make release too (username: `kevin42`).

**Comment by maxpeterson** [comment]
@kevinetienne https://pypi.org/ says 

>User 'kevin42' does not have a verified primary email address and cannot be added as a Maintainer for project.

It seems that you now need to have  verified email address to do anything on pypi.org.

**Comment by maxpeterson** [comment]
@peterfarrell @kevinetienne I have released [2.1.1](https://pypi.org/manage/project/django-pgcrypto-fields/release/2.1.1/)

**Comment by maxpeterson** [comment]
@peterfarrell I have added you (peterfarrell-atdsaa) as a Maintainer to the project on pypi.org,  thanks for getting it working on Django 2.0
