### ISSUE TITLE
Fields are not being decrypted neither with TextDigestField or TextHMACField

### ISSUE THREAD

**Issue by darklow** [incuna/django-pgcrypto-fields#90]
Field was properly encrypted when I create instance, however no decryption is done in any of selects:

```py
from pgcrypto import fields

class Test(models.Model):
    key = fields.TextDigestField()

t = Test(key='asdf')
t.save()
```

```sql
INSERT INTO "app_test" ("key")
VALUES (Digest('*****', 'sha512'), true) RETURNING "app_test"."id";
```

And for any selects I get raw data and selects contain no decryption functions:
```py
for each in Test.objects.all():
    print(each, each.key)
# >>>> object (1) \xd0698d.....
```
SQL:
```sql
SELECT "app_test"."id",
       "app_test"."key"
FROM "app_test";
```

All I added to settings is:
```
PGCRYPTO_KEY = '*****'
# and
'pgcrypto', # To INSTALLED_APPS
```

Versions:
Python 3.6.4
Django 2.1.4 (Also tried Django 2.1.0)
django-pgcrypto-fields==2.5.1

**Comment by peterfarrell** [comment]
There is no decryption with TextDigestField or TextHMACField as they as hash based fields only (https://github.com/incuna/django-pgcrypto-fields#hash-based-fields):

- TextDigestField is hashed in the database using the digest pgcrypto function using the sha512 algorithm.
- TextHMACField is hashed in the database using the hmac pgcrypto function using a key and the sha512 algorithm. This is similar to the digest version however the hash can only be recalculated knowing the key. This prevents someone from altering the data and also changing the hash to match.

If you want to be able to decrypt data, use a SymmetricKeyField or a PublicKeyField:

https://github.com/incuna/django-pgcrypto-fields#django-model-field-equivalents
